project:
  type: website
  output-dir: docs

website:
  title: "title required but not displayed"
  navbar:
    title: false
    left:
      - text: "Emergency Preparedness NW8"
        href: index.qmd
      - Emergency for all 8 Counties.qmd
      - text: "CHB Specific"
        menu:
          - P, N, & M CHB.qmd
          - Quin County CHB.qmd
      - text: "County Specific"
        menu:
          - Kittson.qmd
          - Mahnomen.qmd
          - Marshall.qmd
          - Norman.qmd
          - Pennington.qmd
          - Polk.qmd
          - Red Lake.qmd
          - Roseau.qmd
      - about.qmd
    tools:
      - icon: twitter-x
        href: https://x.com/
      - icon: facebook
        href: https://www.facebook.com/sharer/sharer.php?u=example.org
      - icon: instagram
        href: https://instagram.com
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

editor: visual
